---
title: "M-Competition Data"
author: "David Simbandumwe"
date: "`r Sys.Date()`"
output: openintro::lab_report
---


# Setup

```{r init, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```




```{r load-packages, message=FALSE}

library(dplyr)
library(tidyverse)
library(tsibble)

library(openxlsx)

library(fable)
library(fabletools)
library(yardstick)
library(prophet)
library(lubridate)

library(patchwork)
library(M4comp2018)


```




```{r global_vars}

fileName <- './data/m_indust.xlsx'
#multi_metric <- metric_set(rmse, rsq, mae, mpe, mape, smape, mase)
multi_metric <- metric_set(mape, smape, mase, mpe, rmse)


feqSet <- c("MONTHLY"="months",
            "Monthly"="months",
            "Yearly"="year",
            "Quarterly"="quarter",
            "Weekly"="week",
            "Daily"="daily",
            "Hourly"="hour"
            )


set.seed(808)
test.size <- 20
M_M4 <- Filter(function(l) l$type == "Industry", M4)
n.m4 <- length(M_M4)
indices.m4 <- sample(x=n.m4, size=test.size, replace=FALSE)


```









```{r functions, warning = F, echo = F}



#' calculateMetrics - calculates the performance of the Excel EST forcast function
#'
#' @param new_data 
#' @param modelName 
#' @param datasetName 
#' @param multi_metric 
#'
#' @return dataframe with the performance measurements
#' @export
#'
#' @examples
calculateMetrics <- function(new_data, modelName, datasetName, multi_metric) {
  
  m <- as.data.frame(new_data) %>% dplyr::select(actual,y) %>%  multi_metric(truth=actual, estimate=y)
  m$model <- modelName
  m$dataset <- datasetName
  m$value_round <- round(m$.estimate,3)
  
  return(m)
}



#' plotResults - plot the forcasting results from each of the models and datasets
#'
#' @param train_tb 
#' @param new_data 
#' @param modelName 
#' @param datasetName 
#' @param n 
#' @param perfMetrics 
#'
#' @return NULL
#' @export
#'
#' @examples
plotResults <- function(train_tb, new_data, modelName, datasetName, n, perfMetrics) {

    plt1 <- ggplot() + geom_line(data = train_tb, aes(y=y, x=ds), color="darkgray") +
  		geom_line(data = new_data, aes(y=actual, x=ds), color="darkgray") + 
  		geom_line(data = new_data, aes(y=y, x=ds), color="steelblue", linetype="twodash") 
  
  plt2 <- ggplot() + geom_line(data = new_data, aes(y=actual, x=ds), color="darkgray") + 
  	geom_line(data = new_data, aes(y=y, x=ds), color="steelblue", linetype="twodash") 
  
  plt3 <- perfMetrics %>% dplyr::filter(.metric != 'rmse') %>%
    ggplot(aes(x=value_round, y=.metric, fill=.metric)) +
    coord_flip() + 
    geom_bar(stat = 'identity', width=0.3 ,position=position_dodge()) 

  
  titleStr <- paste0('Forecast ',datasetName,'(',modelName,'):', n )
  suppressWarnings(
    print( ((plt1 / plt2) | plt3) + plot_annotation(title =titleStr))
  )
 
}






#' prophetModel
#'
#' @param train_tb 
#' @param train_rows 
#' @param test_rows 
#' @param new_data 
#'
#' @return
#' @export
#'
#' @examples
prophetModel <- function(train_tb,train_rows, test_rows, new_data) {

  # train model
  fit <- train_tb %>% model(fprophet = fable.prophet::prophet(y, algorithm='LBFGS'))

  # predict
  fc <- fit %>% forecast(new_data = new_data)
  
  
  data_df <- data.frame(
    y =fc$.mean,
    actual = new_data$y,
    ds = new_data$ds
  )
	
	return(data_df)
  
}


#' etsModel
#'
#' @param train_tb 
#' @param train_rows 
#' @param test_rows 
#' @param new_data 
#'
#' @return
#' @export
#'
#' @examples
etsModel <- function(train_tb,train_rows, test_rows, new_data) {

  # train model
  fit <- train_tb %>% model(ets = ETS(y))

  # predict
  fc <- fit %>% forecast(new_data = new_data)
  
  
  data_df <- data.frame(
    y =fc$.mean,
    actual = new_data$y,
    ds = new_data$ds
  )
	
	return(data_df)
  
}



#' arimaModel
#'
#' @param train_tb 
#' @param train_rows 
#' @param test_rows 
#' @param new_data 
#'
#' @return
#' @export
#'
#' @examples
arimaModel <- function(train_tb,train_rows, test_rows, new_data) {

  # train model
  fit <- train_tb %>% model(arima = ARIMA(y))

  # predict
  fc <- fit %>% forecast(new_data = new_data)
  
  
  data_df <- data.frame(
    y =fc$.mean,
    actual = new_data$y,
    ds = new_data$ds
  )
	
	return(data_df)
  
}


```




# Build XLS




```{r}

# create workbook for Excel ETS Models
wb <- createWorkbook()



for (d_set in M_M4[indices.m4]) {


  freq <- as.character(feqSet[as.character(d_set$period)])
  
  # create tain, test and new_data tsibbles
  train_tb <- as_tsibble(d_set$x)
  names(train_tb) <- c('ds','y')
  train_rows <- nrow(train_tb)
  test_tb <- as_tsibble(d_set$xx)
  names(test_tb) <- c('ds','y')
  test_rows <- nrow(test_tb)
  new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
  
  
  
  if (freq %in% c('quarter','months','week','day')) {
     
    train_tb$ds <- as.Date(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- as.Date(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
    
  } else if (freq == 'day') {

    train_tb$ds <- ymd(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- ymd(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
    
  }
  
  
  
    
  # add worksheet
  addWorksheet(wb, sheetName = d_set$st)
  writeData(wb, d_set$st, train_tb, colNames = TRUE)
  writeData(wb, d_set$st, test_tb, colNames = FALSE, startRow = train_rows+2)
  
  # add ETS formula
  v <- list()
  for (i in 1:test_rows) {
     v[i] <- paste0("_xlfn.FORECAST.ETS(A",train_rows+i+1,",B2:B",train_rows+1,",A2:A",train_rows+1,",1)")
   }
  writeFormula(wb, sheet = d_set$st, x = unlist(v) ,startCol = 2, startRow = train_rows+2)
  saveWorkbook(wb, file = fileName, overwrite = TRUE)
    
  
}

# block
n <- readline(prompt=paste0("open and save ", fileName ,": "))
n

```



# Calculate Performance

```{r, warning = F}


#data_M1 <- subset(M1, "INDUST")
final_results_df <- data.frame(
                        .metric = character(),
                        .estimator = character(),
                        .estimate = double(),
                        model = character(),
                        dataset = character(),
                        value_round = double()
)


# load updated workbook
wb <- loadWorkbook(fileName)

for (d_set in M_M4[indices.m4]) {


  freq <- as.character(feqSet[as.character(d_set$period)])
  
  train_tb <- as_tsibble(d_set$x)
  names(train_tb) <- c('ds','y')
  train_tb <-  train_tb %>% update_tsibble(index = ds)
  train_rows <- nrow(train_tb)
  
  test_tb <- as_tsibble(d_set$xx)
  names(test_tb) <- c('ds','y')
  test_tb <-  test_tb %>% update_tsibble(index = ds)
  test_rows <- nrow(test_tb)
  
  new_data <- test_tb %>% select(ds,y) #%>% as_tsibble(index = ds)
  
  
  
   if (freq == 'quarter') {
     
    train_tb$ds <- yearquarter(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- yearquarter(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
    
    
   } else if (freq == 'months') {
    
    train_tb$ds <- yearmonth(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- yearmonth(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
    
  } else if (freq == 'week') {
    
    train_tb$ds <- yearweek(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- yearweek(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
  
  } else if (freq == 'day') {  
    
    train_tb$ds <- ymd(train_tb$ds)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- ymd(test_tb$ds)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% select(ds,y) %>% as_tsibble(index = ds)
    
  } 
  
  

  
  # ets_xls
  sh1 <-readWorkbook(wb, sheet = d_set$st, detectDates=TRUE)
  data_ets <- sh1 %>% dplyr::slice((train_rows+1):(train_rows+test_rows))
  data_ets$actual <- test_tb$y
  
  if (freq == 'quarter') {
      data_ets$ds <- yearquarter(data_ets$ds)
  } else if (freq == 'months') {
      data_ets$ds <- yearmonth(data_ets$ds)
  } else if (freq == 'week') {
      data_ets$ds <- yearweek(data_ets$ds)
  } else if (freq == 'day') {
      data_ets$ds <- ymd(data_ets$ds)
  }
  
  data_ets <- data_ets %>% as_tsibble(index = ds)
  perfMetrics <- calculateMetrics(data_ets, 'ets_xls', d_set$st, multi_metric)
  final_results_df <- bind_rows(final_results_df, perfMetrics)
  plotResults(train_tb, data_ets, 'ets_xls', d_set$st, d_set$n, perfMetrics)
  
  # ETS
  data_ets <- etsModel(train_tb,train_rows, test_rows, new_data)
  perfMetrics <- calculateMetrics(data_ets, 'ETS', d_set$st, multi_metric)
  final_results_df <- bind_rows(final_results_df, perfMetrics)
  plotResults(train_tb, data_ets, 'ETS', d_set$st, d_set$n, perfMetrics)  
  
  
  # ARIMA
  data_arima <- arimaModel(train_tb,train_rows, test_rows, new_data)
  perfMetrics <- calculateMetrics(data_arima, 'ARIMA', d_set$st, multi_metric)
  final_results_df <- bind_rows(final_results_df, perfMetrics)
  plotResults(train_tb, data_arima, 'ARIMA', d_set$st, d_set$n, perfMetrics)  
  

  if (freq == 'year') {

    train_tb$ds <- ymd(train_tb$ds,truncated = 2)
    train_tb <-  train_tb %>% as_tsibble(index = ds)
    test_tb$ds <- ymd(test_tb$ds, truncated = 2)
    test_tb <-  test_tb %>% as_tsibble(index = ds)
    new_data <- test_tb %>% as_tsibble(index = ds)

  }
  
  
  
  # prophet
  tryCatch({
    
    data_prophet <- prophetModel(train_tb,train_rows, test_rows, new_data)
    perfMetrics <- calculateMetrics(data_prophet, 'prophet', d_set$st, multi_metric)
    final_results_df <- bind_rows(final_results_df, perfMetrics)
    plotResults(train_tb, data_prophet, 'Prophet', d_set$st, d_set$n, perfMetrics)  
    
  }, error=function(e) { 
    message(e)
    message(paste0('*** ',d_set$st,': (',freq,' - ' ,d_set$n,')'))
  })
  
  

    


}


```





# Write Results to File

```{r}

#w_flag = FALSE
w_flag = TRUE
if (w_flag) {
	write.csv(final_results_df,file='./results/final_results-05.csv')
}


```





# Read Results from File

```{r}

#r_flag = FALSE
r_flag = TRUE
if (r_flag) {
  result_df <- read_csv('./results/final_results-05.csv') 
}

```



```{r}


result_df %>% dplyr::filter(.metric %in% c('rmse')) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
  labs(
	    x = 'model', 
	    y = 'rmse', 
	    title = 'Model Performance (RMSE)'
	)



result_df %>% dplyr::filter(.metric %in% c('mase')) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
  labs(
	    x = 'model', 
	    y = 'mase', 
	    title = 'Model Performance (MASE)'
	)


result_df %>% dplyr::filter(.metric %in% c('mape')) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
  labs(
	    x = 'model', 
	    y = 'mape', 
	    title = 'Model Performance (MAPE)'
	)



result_df %>% dplyr::filter(.metric %in% c('mase','mape','smape','rmse') ) %>% 
	group_by(model,.metric) %>%
	summarise_at(vars(value_round), list(avg_value = mean)) %>%
	ggplot(aes(x=model, y=avg_value, fill=model)) + 
		geom_bar(stat = 'identity', width=0.3,position=position_dodge()) +
		facet_wrap(vars(.metric),scales = "free", ncol = 4) +
    labs(
  	    x = 'model', 
  	    y = 'performance', 
  	    title = 'Model Performance (MASE/MAPE/SMAPE Avg)'
  	)



```






```{r}

ds_list <- result_df %>% filter(model == 'prophet') %>% select(dataset) %>% distinct()

result_df %>% dplyr::filter(.metric %in% c('rmse') & dataset %in% ds_list$dataset) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
	ggtitle("Model Performance (RMSE)")


result_df %>% dplyr::filter(.metric %in% c('mase') & dataset %in% ds_list$dataset) %>% 
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
	ggtitle("Model Performance (MASE)")


result_df %>% dplyr::filter(.metric %in% c('smape') & dataset %in% ds_list$dataset) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
	ggtitle("Model Performance (sMAPE)")


result_df %>% dplyr::filter(.metric %in% c('mase','mape','smape','rmse') & dataset %in% ds_list$dataset ) %>% 
	group_by(model,.metric) %>%
	summarise_at(vars(value_round), list(avg_value = mean)) %>%
	ggplot(aes(x=model, y=avg_value, fill=model)) + 
		geom_bar(stat = 'identity', width=0.3,position=position_dodge()) +
		facet_wrap(vars(.metric),scales = "free", ncol = 4) +
		ggtitle("Model Performance (MASE/MAPE/SMAPE Avg)")


```




```{r}

result_df %>% dplyr::filter(.metric %in% c('smape') & dataset %in% ds_list$dataset & value_round < 20) %>%
ggplot(aes(x=model, y=value_round, fill=model)) + 
	geom_bar(stat = 'identity', width=0.3, position=position_dodge()) +
	facet_wrap(vars(dataset),scales = "free", ncol = 3) +
	coord_flip() +
	ggtitle("Model Performance (sMAPE)")

result_df %>% dplyr::filter(.metric %in% c('mase','mape','smape','rmse') & 
                              dataset %in% ds_list$dataset & 
                              value_round < 20 ) %>% 
	group_by(model,.metric) %>%
	summarise_at(vars(value_round), list(avg_value = mean)) %>%
	ggplot(aes(x=model, y=avg_value, fill=model)) + 
		geom_bar(stat = 'identity', width=0.3,position=position_dodge()) +
		facet_wrap(vars(.metric),scales = "free", ncol = 4) +
		ggtitle("Model Performance (MASE/MAPE/SMAPE Avg)")

```




```{r}

r_df <- result_df
r_df$freq <- substr(result_df$dataset, 1, 1) 
r_df <- r_df %>% group_by(model,freq,.metric) %>% summarise(mean = mean(.estimate)) %>% dplyr::filter(.metric == 'smape')
r_df$project <- 'ds'
r_df$model[r_df$model == 'ets_xls'] <- 'ETS'

  
r_m4_df <- data.frame(
            'model' = c('ARIMA','ARIMA','ARIMA','ARIMA','ARIMA','ETS','ETS','ETS','ETS','ETS'),
            'freq'= c('D','W','M','Q','Y','D','W','M','Q','Y'),
            '.metric'= c('smape','smape','smape','smape','smape','smape','smape','smape','smape','smape'),
            'mean'= c(3.193,8.653,13.443,10.431,15.168,3.046,8.727,13.525,10.291,15.356)
)
r_m4_df$project <- 'm4'



r_df <- bind_rows(r_df, r_m4_df)


r_df %>% dplyr::filter(freq %in% c('M','Q','Y') & !model %in% c('prophet') ) %>%
	ggplot(aes(x=model, y=mean, fill=project)) + 
		geom_bar(stat = 'identity', width=0.3,position=position_dodge()) +
		facet_wrap(vars(freq),scales = "free", ncol = 3) +
    #coord_flip() +
		ggtitle("Model Performance vs M4")


r_df %>% dplyr::filter(project == 'ds') %>%
	ggplot(aes(x=model, y=mean, fill=model)) + 
		geom_bar(stat = 'identity', width=0.3,position=position_dodge()) +
		facet_wrap(vars(freq),scales = "free", ncol = 4) +
		ggtitle("Model Performance (by freq)")

```


